label_mapping = {
    'Chronic post-COVID-19 syndrome': 'Post-COVID syndrome',
    'Short stature disorder': 'Short stature',
    'Disorder of immune function': 'Immune disorder',
    'Growth hormone deficiency': 'GH deficiency',
    'Chronic ulcerative colitis': 'Ulcerative colitis',
    'Adrenogenital disorder': 'Adrenogenital disorder',
    'Well child (finding)': 'Well child',
    'Periodic fever and aphthous stomatitis with pharyngitis and cervical lymphadenitis syndrome': 'PFAPA syndrome',
    'Celiac disease': 'Celiac disease',
    'Functional abdominal pain syndrome': 'Abdominal pain syndrome',
    'Diabetes mellitus type 1': 'Type 1 diabetes',
    'Cystic fibrosis': 'Cystic fibrosis',
    'Hereditary von Willebrand disease type 1': 'von Willebrand disease',
    'Factor VII deficiency': 'Factor VII deficiency',
    'Familial Mediterranean fever': 'Mediterranean fever',
    'Juvenile idiopathic arthritis, oligoarthritis': 'Juvenile arthritis',
    "Crohn's disease": 'Crohn’s disease',
    'Hereditary factor VIII deficiency disease': 'Factor VIII deficiency',
    'Prader-Willi syndrome': 'Prader-Willi',
    'Asthma': 'Asthma'
}
